name: Java CI
on:
  workflow_dispatch: {}
  push:
    branches:
      - '*'
      - '!gh-pages'
  pull_request:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  build:

    strategy:
      matrix:
        os: [ windows-2016, windows-latest ]
        java:
          # OpenJ9, an alternate JVM implementation.
          # TODO: Replace version by '8' again after problems in 8.0.302+8 on Windows are fixed
          - version: 8.0.292+10
            dist: adopt-openj9
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:

      - name: Set Git options
        # Check out as-is, commit Unix-style line endings
        run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up cache for ~./m2/repository
      #   uses: actions/cache@v2.1.6
      #   with:
      #     path: |
      #       ~/.m2/repository
      #       !~/.m2/repository/dev/aspectj/aspectj-maven-plugin
      #     key: maven-${{ matrix.os }}-java${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       maven-${{ matrix.os }}-java${{ matrix.java }}-
      #       maven-${{ matrix.os }}-

      - name: Set up JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: ${{ matrix.java.version }}
          distribution: ${{ matrix.java.dist }}

      - name: Build with Maven
        run: mvn --show-version --errors --batch-mode "-Dinvoker.streamLogsOnFailures=true" clean verify site
